/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadora_1;

import java.awt.Color;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.JComboBox;

/**
 *
 * @author Informatica
 */
public class Calculadora extends javax.swing.JFrame {

    /**
     * Creates new form Calculadora
     */
    private Color org1;
    private Color org2;
    private Color org3;
    private Color org4;
    private Color org5;
    private Color org6;
    private Color salir1;
    private Color salir2;
    
    
    public double n1;
    public double n2;
    public String operador;
    
    public Calculadora() {
        initComponents();
        this.setLocationRelativeTo(null);
        org1 = siete.getBackground();
        org2 = siete.getForeground();
        org3 = AC.getBackground();
        org4 = AC.getForeground();
        org5 = igual.getBackground();
        org6 = igual.getForeground();
        salir1 = salir.getBackground();
        salir2 = salir.getForeground();

        this.getRootPane().getContentPane().setBackground(this.getBackground());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        siete = new javax.swing.JButton();
        AC = new javax.swing.JButton();
        uno = new javax.swing.JButton();
        cero = new javax.swing.JButton();
        masmenos = new javax.swing.JButton();
        ocho = new javax.swing.JButton();
        dos = new javax.swing.JButton();
        punto = new javax.swing.JButton();
        porc = new javax.swing.JButton();
        nueve = new javax.swing.JButton();
        tres = new javax.swing.JButton();
        igual = new javax.swing.JButton();
        div = new javax.swing.JButton();
        mult = new javax.swing.JButton();
        mas = new javax.swing.JButton();
        cinco = new javax.swing.JButton();
        seis = new javax.swing.JButton();
        menos = new javax.swing.JButton();
        cuatro = new javax.swing.JButton();
        calculos = new javax.swing.JLabel();
        salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setBackground(new java.awt.Color(51, 51, 51));
        setUndecorated(true);

        siete.setBackground(new java.awt.Color(102, 102, 102));
        siete.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        siete.setForeground(new java.awt.Color(255, 255, 255));
        siete.setText("7");
        siete.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        siete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        siete.setFocusPainted(false);
        siete.setFocusable(false);
        siete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sieteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sieteMouseExited(evt);
            }
        });
        siete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sieteActionPerformed(evt);
            }
        });

        AC.setBackground(new java.awt.Color(51, 51, 51));
        AC.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        AC.setForeground(new java.awt.Color(255, 255, 255));
        AC.setText("AC");
        AC.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        AC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AC.setFocusPainted(false);
        AC.setFocusable(false);
        AC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ACMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ACMouseExited(evt);
            }
        });
        AC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACActionPerformed(evt);
            }
        });

        uno.setBackground(new java.awt.Color(102, 102, 102));
        uno.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        uno.setForeground(new java.awt.Color(255, 255, 255));
        uno.setText("1");
        uno.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        uno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        uno.setFocusPainted(false);
        uno.setFocusable(false);
        uno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                unoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                unoMouseExited(evt);
            }
        });
        uno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unoActionPerformed(evt);
            }
        });

        cero.setBackground(new java.awt.Color(102, 102, 102));
        cero.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        cero.setForeground(new java.awt.Color(255, 255, 255));
        cero.setText("0");
        cero.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        cero.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cero.setFocusPainted(false);
        cero.setFocusable(false);
        cero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ceroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ceroMouseExited(evt);
            }
        });
        cero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ceroActionPerformed(evt);
            }
        });

        masmenos.setBackground(new java.awt.Color(51, 51, 51));
        masmenos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        masmenos.setForeground(new java.awt.Color(255, 255, 255));
        masmenos.setText("+/-");
        masmenos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        masmenos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        masmenos.setFocusPainted(false);
        masmenos.setFocusable(false);
        masmenos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                masmenosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                masmenosMouseExited(evt);
            }
        });
        masmenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masmenosActionPerformed(evt);
            }
        });

        ocho.setBackground(new java.awt.Color(102, 102, 102));
        ocho.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ocho.setForeground(new java.awt.Color(255, 255, 255));
        ocho.setText("8");
        ocho.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        ocho.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ocho.setFocusPainted(false);
        ocho.setFocusable(false);
        ocho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ochoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ochoMouseExited(evt);
            }
        });
        ocho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ochoActionPerformed(evt);
            }
        });

        dos.setBackground(new java.awt.Color(102, 102, 102));
        dos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        dos.setForeground(new java.awt.Color(255, 255, 255));
        dos.setText("2");
        dos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        dos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dos.setFocusPainted(false);
        dos.setFocusable(false);
        dos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dosMouseExited(evt);
            }
        });
        dos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosActionPerformed(evt);
            }
        });

        punto.setBackground(new java.awt.Color(102, 102, 102));
        punto.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        punto.setForeground(new java.awt.Color(255, 255, 255));
        punto.setText(".");
        punto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        punto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        punto.setFocusPainted(false);
        punto.setFocusable(false);
        punto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                puntoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                puntoMouseExited(evt);
            }
        });
        punto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puntoActionPerformed(evt);
            }
        });

        porc.setBackground(new java.awt.Color(51, 51, 51));
        porc.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        porc.setForeground(new java.awt.Color(255, 255, 255));
        porc.setText("%");
        porc.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        porc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        porc.setFocusPainted(false);
        porc.setFocusable(false);
        porc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                porcMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                porcMouseExited(evt);
            }
        });
        porc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                porcActionPerformed(evt);
            }
        });

        nueve.setBackground(new java.awt.Color(102, 102, 102));
        nueve.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        nueve.setForeground(new java.awt.Color(255, 255, 255));
        nueve.setText("9");
        nueve.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        nueve.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nueve.setFocusPainted(false);
        nueve.setFocusable(false);
        nueve.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nueveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nueveMouseExited(evt);
            }
        });
        nueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nueveActionPerformed(evt);
            }
        });

        tres.setBackground(new java.awt.Color(102, 102, 102));
        tres.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tres.setForeground(new java.awt.Color(255, 255, 255));
        tres.setText("3");
        tres.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        tres.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tres.setFocusPainted(false);
        tres.setFocusable(false);
        tres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tresMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tresMouseExited(evt);
            }
        });
        tres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tresActionPerformed(evt);
            }
        });

        igual.setBackground(new java.awt.Color(255, 153, 0));
        igual.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        igual.setForeground(new java.awt.Color(255, 255, 255));
        igual.setText("=");
        igual.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        igual.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        igual.setFocusPainted(false);
        igual.setFocusable(false);
        igual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                igualMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                igualMouseExited(evt);
            }
        });
        igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                igualActionPerformed(evt);
            }
        });

        div.setBackground(new java.awt.Color(255, 153, 0));
        div.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        div.setForeground(new java.awt.Color(255, 255, 255));
        div.setText("÷");
        div.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        div.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        div.setFocusPainted(false);
        div.setFocusable(false);
        div.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                divMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                divMouseExited(evt);
            }
        });
        div.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divActionPerformed(evt);
            }
        });

        mult.setBackground(new java.awt.Color(255, 153, 0));
        mult.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        mult.setForeground(new java.awt.Color(255, 255, 255));
        mult.setText("x");
        mult.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        mult.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mult.setFocusPainted(false);
        mult.setFocusable(false);
        mult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                multMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                multMouseExited(evt);
            }
        });
        mult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multActionPerformed(evt);
            }
        });

        mas.setBackground(new java.awt.Color(255, 153, 0));
        mas.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        mas.setForeground(new java.awt.Color(255, 255, 255));
        mas.setText("+");
        mas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        mas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mas.setFocusPainted(false);
        mas.setFocusable(false);
        mas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                masMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                masMouseExited(evt);
            }
        });
        mas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masActionPerformed(evt);
            }
        });

        cinco.setBackground(new java.awt.Color(102, 102, 102));
        cinco.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        cinco.setForeground(new java.awt.Color(255, 255, 255));
        cinco.setText("5");
        cinco.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        cinco.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cinco.setFocusPainted(false);
        cinco.setFocusable(false);
        cinco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cincoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cincoMouseExited(evt);
            }
        });
        cinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cincoActionPerformed(evt);
            }
        });

        seis.setBackground(new java.awt.Color(102, 102, 102));
        seis.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        seis.setForeground(new java.awt.Color(255, 255, 255));
        seis.setText("6");
        seis.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        seis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        seis.setFocusPainted(false);
        seis.setFocusable(false);
        seis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                seisMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                seisMouseExited(evt);
            }
        });
        seis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seisActionPerformed(evt);
            }
        });

        menos.setBackground(new java.awt.Color(255, 153, 0));
        menos.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        menos.setForeground(new java.awt.Color(255, 255, 255));
        menos.setText("-");
        menos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        menos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menos.setFocusPainted(false);
        menos.setFocusable(false);
        menos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menosMouseExited(evt);
            }
        });
        menos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menosActionPerformed(evt);
            }
        });

        cuatro.setBackground(new java.awt.Color(102, 102, 102));
        cuatro.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        cuatro.setForeground(new java.awt.Color(255, 255, 255));
        cuatro.setText("4");
        cuatro.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        cuatro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cuatro.setFocusPainted(false);
        cuatro.setFocusable(false);
        cuatro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cuatroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cuatroMouseExited(evt);
            }
        });
        cuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuatroActionPerformed(evt);
            }
        });

        calculos.setBackground(new java.awt.Color(102, 102, 102));
        calculos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        calculos.setForeground(new java.awt.Color(255, 255, 255));
        calculos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        calculos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        calculos.setOpaque(true);

        salir.setBackground(new java.awt.Color(204, 0, 0));
        salir.setFont(new java.awt.Font("OCR A Std", 1, 14)); // NOI18N
        salir.setForeground(new java.awt.Color(255, 255, 255));
        salir.setText("X");
        salir.setAlignmentY(0.0F);
        salir.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salir.setFocusPainted(false);
        salir.setFocusable(false);
        salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salirMouseExited(evt);
            }
        });
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(calculos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(uno, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dos, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tres, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(punto, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mas, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(igual, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cinco, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(seis, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(menos, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(siete, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AC, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ocho, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(masmenos, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nueve, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(porc, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mult, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(div, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(salir, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(calculos, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(div, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mult, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(porc, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nueve, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(masmenos, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ocho, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AC, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(siete, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menos, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seis, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cinco, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mas, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(igual, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tres, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(punto, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dos, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(uno, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cero, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sieteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sieteMouseEntered
        siete.setBackground(Color.WHITE);
        siete.setForeground(new Color(102,102,102));
        
    }//GEN-LAST:event_sieteMouseEntered

    private void sieteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sieteMouseExited
        siete.setBackground(org1);
        siete.setForeground(org2);
    }//GEN-LAST:event_sieteMouseExited

    private void ACMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ACMouseEntered
        AC.setBackground(Color.WHITE);
        AC.setForeground(new Color(51,51,51));
    }//GEN-LAST:event_ACMouseEntered

    private void ACMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ACMouseExited
        AC.setBackground(org3);
        AC.setForeground(org4);
    }//GEN-LAST:event_ACMouseExited

    private void unoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unoMouseEntered
        uno.setBackground(Color.WHITE);
        uno.setForeground(new Color(102,102,102));
    }//GEN-LAST:event_unoMouseEntered

    private void unoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unoMouseExited
        uno.setBackground(org1);
        uno.setForeground(org2);
    }//GEN-LAST:event_unoMouseExited

    private void ceroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ceroMouseEntered
        cero.setBackground(Color.WHITE);
        cero.setForeground(new Color(102,102,102));
    }//GEN-LAST:event_ceroMouseEntered

    private void ceroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ceroMouseExited
        cero.setBackground(org1);
        cero.setForeground(org2);
    }//GEN-LAST:event_ceroMouseExited

    private void masmenosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masmenosMouseEntered
        masmenos.setBackground(Color.WHITE);
        masmenos.setForeground(new Color(51,51,51));
    }//GEN-LAST:event_masmenosMouseEntered

    private void masmenosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masmenosMouseExited
        masmenos.setBackground(org3);
        masmenos.setForeground(org4);
    }//GEN-LAST:event_masmenosMouseExited

    private void ochoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ochoMouseEntered
        ocho.setBackground(Color.WHITE);
        ocho.setForeground(new Color(102,102,102));
    }//GEN-LAST:event_ochoMouseEntered

    private void ochoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ochoMouseExited
       ocho.setBackground(org1);
       ocho.setForeground(org2);
    }//GEN-LAST:event_ochoMouseExited

    private void dosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dosMouseEntered
        dos.setBackground(Color.WHITE);
        dos.setForeground(new Color(102,102,102));
    }//GEN-LAST:event_dosMouseEntered

    private void dosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dosMouseExited
        dos.setBackground(org1);
        dos.setForeground(org2);
    }//GEN-LAST:event_dosMouseExited

    private void puntoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_puntoMouseEntered
        punto.setBackground(Color.WHITE);
        punto.setForeground(new Color(102,102,102));
    }//GEN-LAST:event_puntoMouseEntered

    private void puntoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_puntoMouseExited
        punto.setBackground(org1);
        punto.setForeground(org2);
    }//GEN-LAST:event_puntoMouseExited

    private void porcMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_porcMouseEntered
        porc.setBackground(Color.WHITE);
        porc.setForeground(new Color(51,51,51));
    }//GEN-LAST:event_porcMouseEntered

    private void porcMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_porcMouseExited
        porc.setBackground(org3);
        porc.setForeground(org4);
    }//GEN-LAST:event_porcMouseExited

    private void nueveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nueveMouseEntered
        nueve.setBackground(Color.WHITE);
        nueve.setForeground(new Color(102,102,102));
    }//GEN-LAST:event_nueveMouseEntered

    private void nueveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nueveMouseExited
        nueve.setBackground(org1);
        nueve.setForeground(org2);
    }//GEN-LAST:event_nueveMouseExited

    private void tresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tresMouseEntered
        tres.setBackground(Color.WHITE);
        tres.setForeground(new Color(102,102,102));
    }//GEN-LAST:event_tresMouseEntered

    private void tresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tresMouseExited
        tres.setBackground(org1);
        tres.setForeground(org2);
    }//GEN-LAST:event_tresMouseExited

    private void igualMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_igualMouseEntered
        igual.setBackground(Color.WHITE);
        igual.setForeground(new Color(255,153,0));
    }//GEN-LAST:event_igualMouseEntered

    private void igualMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_igualMouseExited
        igual.setBackground(org5);
        igual.setForeground(org6);
    }//GEN-LAST:event_igualMouseExited

    private void divMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_divMouseEntered
        div.setBackground(Color.WHITE);
        div.setForeground(new Color(255,153,0));
    }//GEN-LAST:event_divMouseEntered

    private void divMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_divMouseExited
        div.setBackground(org5);
        div.setForeground(org6);
    }//GEN-LAST:event_divMouseExited

    private void multMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_multMouseEntered
        mult.setBackground(Color.WHITE);
        mult.setForeground(new Color(255,153,0));
    }//GEN-LAST:event_multMouseEntered

    private void multMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_multMouseExited
        mult.setBackground(org5);
        mult.setForeground(org6);
    }//GEN-LAST:event_multMouseExited

    private void masMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masMouseEntered
        mas.setBackground(Color.WHITE);
        mas.setForeground(new Color(255,153,0));
    }//GEN-LAST:event_masMouseEntered

    private void masMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masMouseExited
        mas.setBackground(org5);
        mas.setForeground(org6);
    }//GEN-LAST:event_masMouseExited

    private void cincoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cincoMouseEntered
        cinco.setBackground(Color.WHITE);
        cinco.setForeground(new Color(102,102,102));
    }//GEN-LAST:event_cincoMouseEntered

    private void cincoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cincoMouseExited
        cinco.setBackground(org1);
        cinco.setForeground(org2);
    }//GEN-LAST:event_cincoMouseExited

    private void seisMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seisMouseEntered
        seis.setBackground(Color.WHITE);
        seis.setForeground(new Color(102,102,102));
    }//GEN-LAST:event_seisMouseEntered

    private void seisMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seisMouseExited
        seis.setBackground(org1);
        seis.setForeground(org2);
    }//GEN-LAST:event_seisMouseExited

    private void menosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menosMouseEntered
        menos.setBackground(Color.WHITE);
        menos.setForeground(new Color(255,153,0));
    }//GEN-LAST:event_menosMouseEntered

    private void menosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menosMouseExited
        menos.setBackground(org5);
        menos.setForeground(org6);
    }//GEN-LAST:event_menosMouseExited

    private void cuatroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuatroMouseEntered
        cuatro.setBackground(Color.WHITE);
        cuatro.setForeground(new Color(102,102,102));
    }//GEN-LAST:event_cuatroMouseEntered

    private void cuatroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuatroMouseExited
        cuatro.setBackground(org1);
        cuatro.setForeground(org2);
    }//GEN-LAST:event_cuatroMouseExited

    private void salirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseEntered
        salir.setBackground(Color.WHITE);
        salir.setForeground(new Color(204,0,0));
    }//GEN-LAST:event_salirMouseEntered

    private void salirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseExited
        salir.setBackground(salir1);
        salir.setForeground(salir2);
    }//GEN-LAST:event_salirMouseExited

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        this.dispose();
    }//GEN-LAST:event_salirActionPerformed

    private void ceroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ceroActionPerformed
        this.calculos.setText(this.calculos.getText() + "0");
    }//GEN-LAST:event_ceroActionPerformed

    private void puntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puntoActionPerformed
        if(!(this.calculos.getText().contains(".")))
        this.calculos.setText(this.calculos.getText() + ".");
    }//GEN-LAST:event_puntoActionPerformed

    private void unoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unoActionPerformed
        this.calculos.setText(this.calculos.getText() + "1");
    }//GEN-LAST:event_unoActionPerformed

    private void dosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosActionPerformed
        this.calculos.setText(this.calculos.getText() + "2");
    }//GEN-LAST:event_dosActionPerformed

    private void tresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tresActionPerformed
        this.calculos.setText(this.calculos.getText() + "3");
    }//GEN-LAST:event_tresActionPerformed

    private void cuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuatroActionPerformed
        this.calculos.setText(this.calculos.getText() + "4");
    }//GEN-LAST:event_cuatroActionPerformed

    private void cincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cincoActionPerformed
        this.calculos.setText(this.calculos.getText() + "5");
    }//GEN-LAST:event_cincoActionPerformed

    private void seisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seisActionPerformed
        this.calculos.setText(this.calculos.getText() + "6");
    }//GEN-LAST:event_seisActionPerformed

    private void sieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sieteActionPerformed
        this.calculos.setText(this.calculos.getText() + "7");
    }//GEN-LAST:event_sieteActionPerformed

    private void ochoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ochoActionPerformed
        this.calculos.setText(this.calculos.getText() + "8");
    }//GEN-LAST:event_ochoActionPerformed

    private void nueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nueveActionPerformed
        this.calculos.setText(this.calculos.getText() + "9");
    }//GEN-LAST:event_nueveActionPerformed

    private void ACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACActionPerformed
        this.calculos.setText("");
    }//GEN-LAST:event_ACActionPerformed

    private void masActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masActionPerformed
        this.n1 = Double.parseDouble(this.calculos.getText());
        this.operador = "+";
        this.calculos.setText("");
        
    }//GEN-LAST:event_masActionPerformed

    private void igualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_igualActionPerformed
        this.n2 = Double.parseDouble(this.calculos.getText());
        
        
        double porciento = n2*0.01;
        switch(this.operador)
        {
            case "+": this.calculos.setText(cero_no(this.n1+this.n2));
            break;
            
            case "-":this.calculos.setText(cero_no(this.n1-this.n2));
            break;
            
            case "x": this.calculos.setText(cero_no(this.n1*this.n2));
            break;
            
            case "%": this.calculos.setText(cero_no(this.n1*porciento));
            break;
            
            case "/": 
                if(this.n1 == 0 || this.n2 == 0)
                    this.calculos.setText("Syntax Error");
                else
                    this.calculos.setText(cero_no(this.n1/this.n2));
            break;
            
        }
        
        double resultado = 0;
        String n3 = cero_no(n1);
        String n4 = cero_no(n2);
        
        switch(this.operador) {
            case "+": 
                resultado = this.n1 + this.n2;
                break;
            case "-":
                resultado = this.n1 - this.n2;
                break;
            case "x": 
                resultado = this.n1 * this.n2;
                break;
            case "%": 
                resultado = this.n1 * (this.n2 * 0.01);
                break;
            case "/": 
                if(this.n1 == 0 || this.n2 == 0) {
                    System.out.println(n3 + " " + this.operador + " "+ n4+ " = "+ "Syntax Error");
                    return;
                } else {
                    resultado = this.n1 / this.n2;
                }
                break;
        }
        
        String resultadoStr = cero_no(resultado);
        
        String ecuacion = n3 + " " + this.operador + " " + n4 + " = ";
        System.out.println(ecuacion + resultadoStr);
    }//GEN-LAST:event_igualActionPerformed

    private void menosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menosActionPerformed
        this.n1 = Double.parseDouble(this.calculos.getText());
        this.operador = "-";
        this.calculos.setText("");
    }//GEN-LAST:event_menosActionPerformed

    private void multActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multActionPerformed
        this.n1 = Double.parseDouble(this.calculos.getText());
        this.operador = "x";
        this.calculos.setText("");
    }//GEN-LAST:event_multActionPerformed

    private void divActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divActionPerformed
        this.n1 = Double.parseDouble(this.calculos.getText());
        this.operador = "/";
        this.calculos.setText("");
    }//GEN-LAST:event_divActionPerformed

    private void masmenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masmenosActionPerformed
        Signomenos();
    }//GEN-LAST:event_masmenosActionPerformed

    private void porcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_porcActionPerformed
        this.n1 = Double.parseDouble(this.calculos.getText());
        this.operador = "%";
        this.calculos.setText("");
    }//GEN-LAST:event_porcActionPerformed
 
    public void Signomenos() {
    String signos = this.calculos.getText();
    
        if (signos.startsWith("-")) 
            this.calculos.setText(signos.substring(1));
         
        else 
            this.calculos.setText("-" + signos);
    }
    
    public String cero_no(double resul)
    {
        
        String retorno = "";
        retorno = Double.toString(resul);
        
        if(resul%1 == 0)
        {
            retorno = retorno.substring(0, retorno.length()-2);
            
        }
        
        return retorno;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AC;
    private javax.swing.JLabel calculos;
    private javax.swing.JButton cero;
    private javax.swing.JButton cinco;
    private javax.swing.JButton cuatro;
    private javax.swing.JButton div;
    private javax.swing.JButton dos;
    private javax.swing.JButton igual;
    private javax.swing.JButton mas;
    private javax.swing.JButton masmenos;
    private javax.swing.JButton menos;
    private javax.swing.JButton mult;
    private javax.swing.JButton nueve;
    private javax.swing.JButton ocho;
    private javax.swing.JButton porc;
    private javax.swing.JButton punto;
    private javax.swing.JButton salir;
    private javax.swing.JButton seis;
    private javax.swing.JButton siete;
    private javax.swing.JButton tres;
    private javax.swing.JButton uno;
    // End of variables declaration//GEN-END:variables
}
